name: Test/Build/Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: "Check & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml') }}

      - name: Cache rust build files
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    name: "Build & Push Image"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - check
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: ghcr.io/lucaspickering/osrs-hiscore-proxy:latest
          pull: true
          push: true
